name: 🐞 Bug
description: Something is not working as intended.
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
    placeholder: |
      When I do <X>, <Y> happens and I see the error message attached below:
      ```...```
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
    placeholder: When I do <X>, <Z> should happen instead.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Koko version
    description: |
      example: v0.1.0
    placeholder: 'Please provide your version of Koko here.'
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: Kong Gateway version
    description: |
      example: 3.0.1
    placeholder: 'Please provide your version of Kong Gateway used with Koko here.'
    render: shell
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering?

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
