name: dev-build
on:
  push:
    branches:
    - main
jobs:
  build-docker:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Source Code
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set tag
        id: tag
        run: |
          echo "::set-output name=tag::$(git rev-parse --short HEAD)"
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: kong/koko:dev-latest,kong/koko:dev-${{ steps.tag.outputs.tag }}

