name: Integration Tests [OSS]
on: pull_request
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        kong_image:
        - 'kong:2.5.1'
        - 'kong:2.6.0'
        - 'kong:2.7.0'
        - 'kong:2.8.0'
        - 'kong:3.0.0'
        - 'kong:3.1.0'
        include:
          - kong_image: 'kong/kong:master-alpine' # tracks mainline branch of kong/kong
            experimental: false
    env:
      KOKO_TEST_KONG_DP_IMAGE: ${{ matrix.kong_image }}
    steps:
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
        check-latest: true
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-integration-${{ hashFiles('**/go.sum') }}
    - name: Cache go-atc-router library
      id: cache-atc
      uses: actions/cache@v3
      with:
        path: |
          /tmp/libatc_router*
        key: ${{ runner.os }}-go-atc-router-${{ hashFiles('**/go.sum') }}
    - name: Install cached library
      if: steps.cache-atc.outputs.cache-hit == 'true'
      run: |
        sudo install /tmp/libatc_router* /usr/local/lib
    - name: make test-integration
      continue-on-error: ${{ matrix.experimental }}
      run: make test-integration

