name: "PR label check"
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]
jobs:
  check-labels:
    name: prevent merge labels
    runs-on: ubuntu-latest
    steps:
    - uses: mheap/github-action-required-labels@v1
      with:
        mode: exactly
        count: 0
        labels: "hold/do-not-merge"
