name: govulncheck
on: pull_request
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: make install-tools
      run: make install-tools
    - name: govulncheck
      run: govulncheck ./...
