name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/kong/go-wrpc
    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup private modules
      run: |
          git config --global url."https://${{ secrets.GO_WRPC_MODULE_TOKEN }}:x-oauth-basic@github.com/kong/go-wrpc".insteadOf "https://github.com/kong/go-wrpc"
    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: make install-tools
      run: make install-tools
    - name: make verify
      run: make gen-verify
    - name: make test
      run: make test

