name: unit-test
on: pull_request
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database:
        - sqlite3
        - postgres
    env:
      KOKO_TEST_DB: ${{ matrix.database }}
    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-unit-${{ hashFiles('**/go.sum') }}
    - name: setup-db
      run: ./scripts/setup-db.sh &
    - name: make test-race
      run: make test-race

