name: Unit Tests [OSS]
on: pull_request
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        database:
        - sqlite3
        - postgres
        - mysql
    env:
      KOKO_TEST_DB: ${{ matrix.database }}
    steps:
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
        check-latest: true
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-unit-${{ hashFiles('**/go.sum') }}
    - name: setup-db
      run: |
        ./scripts/setup-db.sh ${{ matrix.database }} &
        ./scripts/wait-for-db.sh ${{ matrix.database }}
    - name: Cache go-atc-router library
      id: cache-atc
      uses: actions/cache@v3
      with:
        path: |
          /tmp/libatc_router*
        key: ${{ runner.os }}-go-atc-router-${{ hashFiles('**/go.sum') }}
    - name: Install cached library
      run: |
        if [ -e /tmp/libatc_router* ]; then
          sudo install /tmp/libatc_router* /usr/local/lib;
        else
          make install-deps
        fi
    - name: make test-race
      run: make test-race

